name: Build and deploy a container to an Azure Container Registry

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to azure
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build the container
        run: |
          docker build --file Dockerfile.prod \
          -t ${{secrets.ACR_SERVER}}/settled-server:${{ github.sha }} \
          -t ${{secrets.ACR_SERVER}}/settled-server:latest \
          .

      - name: Deploy to Azure Container Registry
        run: |
          docker push ${{secrets.ACR_SERVER}}/settled-server:${{ github.sha }}
          docker push ${{secrets.ACR_SERVER}}/settled-server:latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Web App Restart
        run: az webapp restart --resource-group settled --name settled-server
